# This workflow is made to deploy docs to github pages
# So it focuses only on packages/docs
name: Github Pages

# Uncomment this part for the workflow to be triggered
# on:
#   release:
#     # Run every time a github release is created
#     types: [created]
#   push:
#     # Run only on main branch
#     branches:
#       - "main"
#     # Run only if files modified are not in lib package
#     # and are not github docs
#     paths-ignore:
#       - "packages/lib/**"
#       - "*.md"
#       - ".github/docs/**"
#   pull_request:
#     # Run only on main branch
#     branches:
#       - "main"
#     # Run only if files modified are not in lib package
#     # and are not github docs
#     paths-ignore:
#       - "packages/lib/**"
#       - "*.md"
#       - ".github/docs/**"

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  # Build
  build:
    name: Build
    # Build only if commit message contains "[deploy]" option
    # Either it will stop workflow because deploy job needs build job
    if: "github.event_name == 'release' || contains(github.event.head_commit.message, '[deploy]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      # ----------------------------------
      #           Yarn cache
      # ----------------------------------
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      # ----------------------------------
      #           Yarn cache
      # ----------------------------------

      # Install dependencies
      - name: INSTALL
        # Install dependencies only if cache was not found to accelerate workflow
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      # Build all packages (lib, docs)
      # We also build packages/lib because it is used in packages/docs
      - name: BUILD
        run: yarn build:ci

      # ----------------------------------
      #         Upload artifacts
      # ----------------------------------
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
      # ----------------------------------
      #         Upload artifacts
      # ----------------------------------

  # Deploy to gh pages
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    # Manual deployment
    # See https://devblogs.microsoft.com/devops/i-need-manual-approvers-for-github-actions-and-i-got-them-now/
    environment:
      name: username.github.io/example
      url: https://username.github.io/example/
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "12"

      # ----------------------------------
      #     Download dist artifacts
      # ----------------------------------
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/
      # ----------------------------------
      #     Download dist artifacts
      # ----------------------------------

      # Deploy dist folder to gh pages
      - name: DEPLOY
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ env.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: ${{ secrets.GIT_AUTHOR_NAME }}
          user_email: ${{ secrets.GIT_AUTHOR_EMAIL }}